### ISSUE TITLE
Filter entries by author

### ISSUE THREAD

**Issue by KatieMFritz** [masugadesign/cp-filters-craft-cms#10]
**Is your feature request related to a problem? Please describe.**  
I'm using CP Filters to help academics manage a database of submitted papers. They want to be able to easily pull up papers by a specific author.

**Describe the solution you'd like**  
Allow me to filter entries by the Craft native Author metadata.

**Describe alternatives you've considered**  
Using Searchit; sorting by author instead.

**Additional context**  
Would like `Author` as an option in addition to `id`, `Title`, `Slug` and other native fields. I assume it's harder to implement or you would have already done it. 😅

<img width="381" alt="Screen Shot 2020-12-15 at 5 18 40 PM" src="https://user-images.githubusercontent.com/7085184/102279597-a9b62f00-3ef9-11eb-944a-58dcb742b784.png">

**Comment by benjaminkohl** [comment]
I am sorry for the late response on this request. I am actually unsure why author is not one of the filterable criteria. I'd have to look into that one and see if there was an issue with it. It might be that we have to add two options, one for Author ID and one for Author Email, but I am just speculating.

**Comment by benjaminkohl** [comment]
We just released v2.1.0 which supports filtering entries by Author ID.
