### ISSUE TITLE
Unable to install to 3.6

### ISSUE THREAD

**Issue by chrisrowe** [masugadesign/cp-filters-craft-cms#11]
I'm aware 3.6 only just dropped but Composer requirements prevent this being installed.
 https://github.com/masugadesign/cp-filters-craft-cms/blob/master/composer.json#L8

**Comment by benjaminkohl** [comment]
Yes, there was no way to know if the last version of the plugin was compatible with Craft 3.6 prior to its release. We just release CP Filters v1.1.1 with Craft 3.6 support.
