### ISSUE TITLE
Related Field Filter Dropdown Select is Limited to Only ~100 Entries

### ISSUE THREAD

**Issue by AbbeyDesign** [masugadesign/cp-filters-craft-cms#12]
When filtering by a Related Entries Field and choosing "is assigned" the resulting Select Dropdown only shows the first 100 entries.

**Expected behavior**  
Currently have about 600 entries and I should see all of them.

**Craft Version & Installed Plugin Version**  
Craft:   3.6.11.2
Plugin: CP filters
Mac: Chrome and Firefox

**Comment by benjaminkohl** [comment]
This issue has been resolved as of v1.1.1.3. The queries that populate those filter value selects are no longer limited and those selects are now SlimSelect elements so finding a particular value in a long list of options is much easier.
