### ISSUE TITLE
SuperTable Support

### ISSUE THREAD

**Issue by john-henry** [masugadesign/cp-filters-craft-cms#13]
Hi there,

wonderful plugin and clients love it. They have quite a few SuperTable fields though

Craft: 3.5.19.1
CPFilters : 1.1.1

I've added Supertable as a test to see if compatible with my cpfilters.php

```
'additionalFieldTypes' => [
		'verbb\supertable\fields\SuperTableField' => ['contains']
	],
```

While it displays the fields in the filters it does not return results. Fields have search turned on.

Has anybody succeeded in doing this yet? have you tried it yourself?

**Comment by john-henry** [comment]
Hi @ryanmasuga can you confirm either way if this should work or not?

**Comment by benjaminkohl** [comment]
For Super Table fields, support is most likely limited to the "is empty" and "is not empty" filters much like the Matrix field type but I can't recall if we've tested those with a Super Table field to confirm they work similarly.
