### ISSUE TITLE
Issue when filtering between 2 dates.

### ISSUE THREAD

**Issue by Geestig** [masugadesign/cp-filters-craft-cms#14]
**Describe the bug**  
Whenever I try to filter between 2 dates, the results are not correct it seems as if the relation between the 2 dates has an OR relation. 

Example:
2 different fields and dates returns the correct data.
![image](https://user-images.githubusercontent.com/9035369/117275578-75b6b880-ae5e-11eb-85aa-f2a46d7e2a8d.png)

2 same fields with different dates returns pretty much everything
![image](https://user-images.githubusercontent.com/9035369/117275727-a139a300-ae5e-11eb-988f-a1a35aea1b72.png)

EDIT: The order of the greater than and less than also makes a difference,
![image](https://user-images.githubusercontent.com/9035369/117276726-78fe7400-ae5f-11eb-96b4-8ad42d76c1b4.png)
![image](https://user-images.githubusercontent.com/9035369/117276805-8ae01700-ae5f-11eb-9224-6ea2baf50102.png)

Even when changing the dates returns the same data:
![image](https://user-images.githubusercontent.com/9035369/117277573-4bfe9100-ae60-11eb-8746-7742982a1c39.png)

**Craft Version & Installed Plugin Version**  
Craft: Craft CMS 3.5.15.1
Plugin: 1.1.1

**To Reproduce**  
_Steps to reproduce the behavior:_
1. Add 2 rows with the same 'date' field (post date, date created, etc.)
2. enter 2 dates to show a list of items between the 2 dates
3. See wrong data

**Expected behavior**  
It should show a correct list between the 2 dates.

**Comment by benjaminkohl** [comment]
Thank you for bringing this to our attention. I'm thinking we may need to revise how the criteria array is constructed to account for multiple filters for a single field.

**Comment by Geestig** [comment]
Any update regarding this issue?

**Comment by benjaminkohl** [comment]
We just released CP Filters v1.1.1.2 which contains the fix for this issue. All fields now support multiple criteria. https://github.com/masugadesign/cp-filters-craft-cms/blob/master/CHANGELOG.md#1112---2021-06-30
