### ISSUE TITLE
Ability to set Filters for Commerce Products

### ISSUE THREAD

**Issue by emilyfitton** [masugadesign/cp-filters-craft-cms#16]
**Is your feature request related to a problem? Please describe.**  
I know it's already in your Roadmap, but I'd love to have these filters for Commerce Products. I have a site with over 6000 products and these filters would really help with the management of them.

**Describe alternatives you've considered**  
If you can let me know a rough timeline for when you'll be looking to add products? If it's not soon are you happy for me to add the feature and do a PR for you?

**Comment by goraxan** [comment]
I'm also interested on this feature, do you have any plans to add it?

**Comment by ryanmasuga** [comment]
I think we have something workable that we can release for Commerce products. We need a bit more testing, but will post here when there is something to share.

**Comment by ryanmasuga** [comment]
With [version 1.2.0](https://github.com/masugadesign/cp-filters-craft-cms/commit/236c8ac5ef8724b9e86f2a0455605027613a9f0a), you can now filter Craft Commerce Products and Orders with CP Filters.
