### ISSUE TITLE
Screenshots on Craft Plugin Store is too small

### ISSUE THREAD

**Issue by nitech** [masugadesign/cp-filters-craft-cms#17]
Proably better sales if you add higher resolution to those screenshots -- and perhaps screenshots that cover more of the features in the plugin :-)

**Comment by ryanmasuga** [comment]
The thumbnails look terrible, sure, but you can click on them to open them in a "modal" where you can see details.

**Comment by nitech** [comment]
Ah, strange. When I tested it, it didn't actually download higher resolution screenshots but only enlarged the thumbnails. Must have been a bug.
