### ISSUE TITLE
Add filters to Asset page

### ISSUE THREAD

**Issue by zawilliams** [masugadesign/cp-filters-craft-cms#19]
Is there a way to add saved filters to the Assets page filters?

Like here:

<img width="498" alt="Screen Shot 2022-05-18 at 1 59 50 PM" src="https://user-images.githubusercontent.com/1509011/169154896-4fa4d1d1-b7a6-46ef-a17f-8bf413ed6e58.png">

**Comment by benjaminkohl** [comment]
No, there is not. All the element filtering takes place in the CP Filters pages of the control panel and it doesn't attempt to manipulate how Craft's native element indexes operate.

**Comment by zawilliams** [comment]
@benjaminkohl ok got it. Thanks for the quick response!

**Comment by zawilliams** [comment]
@benjaminkohl I had wrongly assumed this plugin had that functionality and had a client purchase this plugin. Is it possible to get a refund?

**Comment by ryanmasuga** [comment]
You'd have to go through Pixel & Tonic for any refunds, as they run the marketplace. From their [terms](https://craftcms.com/terms-of-use), 

> We have a 30-day refund policy for Craft licenses and plugin licenses sold through the Plugin Store. Please email [sales@craftcms.com](mailto:sales@craftcms.com) with your order number to request a refund.

**Comment by zawilliams** [comment]
@ryanmasuga got it. Thanks!
