### ISSUE TITLE
Multi-site support

### ISSUE THREAD

**Issue by bliswebagency** [masugadesign/cp-filters-craft-cms#4]
Just installed on a multi-site but I can only see entries from the default site. Is this something that you guys plan to add anytime soon?

**Comment by ryanmasuga** [comment]
We originally built this for us - and we have no existing client sites that use multi-site We're not sure what the level of effort would be here.

How would you envision it working? Always seeing entries from all sites by default, and then some sort of site filter?

**Comment by bliswebagency** [comment]
I just picture it working as a drop down like Entries does.

Example: http://shared.bl.ms/ZIR97n

In terms of effort required, it should be relatively straight forward. The current plugin is already filtering by site - it's just using the default site id given it's not been defined.

By adding a drop down, it would just allow people to define a different site id to the default.

If we took a pass at building this feature, would you consider including it?

**Comment by bliswebagency** [comment]
Just ran a super quick test which seemed to work.

Line 54 of /src/templates/_index.twig allows you to define the siteId:

`{% set filteredElements = craft.cpfilters.elementQuery(elementClass, criteria).orderBy('dateCreated', 'desc').siteId(1).limit(limit).offset(offset).all() %}`

By adding a drop down that allows us to define that ID, you'll pretty much have this thing multi-site compatible.

**Comment by ryanmasuga** [comment]
I think multi-site support sounds good, and thanks for testing. We have a few things to think through with it. 

We might take a crack at this first before working with pull requests.

**Comment by benjaminkohl** [comment]
The ability to filter by siteId has been added to the 1.1.0 branch. When no siteId filter is provided, it will not filter by site.

**Comment by benjaminkohl** [comment]
We went ahead and released v1.0.2 with this feature while v1.1.0 is still in development. Included in this release is a fix for the changelog URL which is why this update won't appear in Craft control panels until it is installed.
