### ISSUE TITLE
Lighswitch fields aren't showing

### ISSUE THREAD

**Issue by arifje** [masugadesign/cp-filters-craft-cms#6]
We have some custom fields with type lightswitch, but in the filter they aren't popping up. Seems to limited to other field types only.

**Comment by benjaminkohl** [comment]
The ability to filter by lightswitch field values has been added to the 1.1.0 branch.

**Comment by benjaminkohl** [comment]
We went ahead and released v1.0.2 with Lightswitch field support while v1.1.0 is still in development. Included in this release is a fix for the changelog URL which is why this update won't appear in Craft control panels until it is installed.
