### ISSUE TITLE
Clicking next page on users or assets tab reverts active tab to entries 

### ISSUE THREAD

**Issue by keithmancuso** [masugadesign/cp-filters-craft-cms#7]
**Describe the bug**
Clicking next page on users or assets tab reverts active tab to entries. Seems like its just not preserving the active tab.

**To Reproduce**
1. Go to 'the assets tab'
2. Click on 'the next page buttons'
3. Scroll down to 'results and see the second page of entries, not assets'

**Expected behavior**

should show second page of assets!

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ryanmasuga** [comment]
We need to update our issue template, apparently, because we failed to ask: what Craft version and installed plugin version?

**Comment by keithmancuso** [comment]
Hey @ryanmasuga sorry for the delay here

this is craft version  3.5.17.1

and the plugin version  1.0.0

**Comment by ryanmasuga** [comment]
Version 1.1.0 came out Jan 5 (which added Saved Filters). It didn't necessarily handle the issue you had, but if you install 1.1.0, is the issue still happening for you?

**Comment by Nicovery** [comment]
Hi we have the same issue. 

Craft : 3.6.12
plugin : 1.1.1

It seems to be fixed on the futur version. Any idea when this version will come out ?

**Comment by benjaminkohl** [comment]
We just released v1.1.1.1 which contains a fix for the pagination URLs using the wrong element type. It also adds First Name and Last Name filters for the User element.

**Comment by Nicovery** [comment]
Thank you very much !
